Improve lpass credential helper to handle token

diff --git a/bin/git-credential-lastpass b/bin/git-credential-lastpass
--- a/bin/git-credential-lastpass
+++ b/bin/git-credential-lastpass
@@ -8,50 +8,50 @@
 
 declare -A params
 
-if [ "x$1" == "x-l" ]; then
+if [[ $1 == -l ]]; then
     shift
     lpassuser=$1
     shift
 fi
 
-if [ "x$1" == "xget" ]; then
+if [[ $1 == get ]]; then
     read -r line
-    while [ -n "$line" ]; do
+    while [[ -n $line ]]; do
         key=${line%%=*}
         value=${line#*=}
         params[$key]=$value
         read -r line
     done
 
-    if [ "x${params['protocol']}" != "xhttps" ]; then
+    if [[ ${params["protocol"]} != https ]]; then
         exit
     fi
 
-    if [ -z "${params["host"]}" ]; then
+    if [[ -z ${params["host"]} ]]; then
         exit
     fi
 
-    if ! lpass ls >/dev/null 2>&1; then
-        if [ -z "$lpassuser" ]; then
+    if ! lpass status &>/dev/null; then
+        # TODO: should we just quit here?
+        if [[ -z $lpassuser ]]; then
             read -r -p "Lastpass username: " lpassuser </dev/tty >/dev/tty
-        fi
-        if [ -z "$lpassuser" ]; then
-            exit
+            if [[ -z $lpassuser ]]; then
+                echo "Failed to get lastpass username" >&2
+                exit 1
+            fi
         fi
         if ! lpass login "$lpassuser"; then
-            echo "Failed to login to lastpass" >/dev/stderr
-            exit
+            echo "Failed to login to lastpass" >&2
+            exit 1
         fi
     fi
 
-    user=$(lpass show --username "${params["host"]}")
-    pass=$(lpass show --password "${params["host"]}")
-
-    if [ "x$user" == "x" ] || [ "x$pass" == "x" ]; then
-        echo "Couldn't find host in lastpass DB." >/dev/stderr
-        exit
+    # Use jq to get username/password with one call to lpass
+    out=$(lpass show -j "git_${params['host']}" 2>/dev/null | jq -r '.[] | "username=\(.username)\npassword=\(.password)"')
+    # If entry doesn't exist in lastpass, string should be blank
+    if [[ -z $out ]]; then
+        echo "Couldn't find credential for host ${params['host']} in lastpass" >&2
+        exit 1
     fi
-
-    echo username="$user"
-    echo password="$pass"
+    echo "$out"
 fi
