Use two commands for lpass rather than jq

diff --git a/bin/git-credential-lastpass b/bin/git-credential-lastpass
--- a/bin/git-credential-lastpass
+++ b/bin/git-credential-lastpass
@@ -46,12 +46,12 @@ if [[ $1 == get ]]; then
         fi
     fi
 
-    # Use jq to get username/password with one call to lpass
-    out=$(lpass show -j "git_${params['host']}" 2>/dev/null | jq -r '.[] | "username=\(.username)\npassword=\(.password)"')
-    # If entry doesn't exist in lastpass, string should be blank
-    if [[ -z $out ]]; then
-        echo "Couldn't find credential for host ${params['host']} in lastpass" >&2
+    user=$(lpass show --username "git_${params["host"]}")
+    pass=$(lpass show --password "git_${params["host"]}")
+    if [[ -z $user ]] || [[ -z $pass ]]; then
+        echo "Couldn't find credential for host git_${params['host']} in lastpass" >&2
         exit 1
     fi
-    echo "$out"
+    echo "username=$user"
+    echo "password=$pass"
 fi
