Set $fish_sequence_key_delay_ms

diff --git a/bin/git-credential-op b/bin/git-credential-op
--- a/bin/git-credential-op
+++ b/bin/git-credential-op
@@ -33,7 +33,7 @@ if [[ $1 == get ]]; then
 
     if ! op whoami &>/dev/null; then
         # TODO: should we just quit here?
-        echo "Log in to 1password cli" >&2
+        printf "\033[38;5;196mERROR: not logged in to 1password cli\033[0m\n" >&2
         exit 1
     fi
 
